<h2>Homework 2</h2>

In [1]:
from sklearn.datasets import load_boston
import pandas as pd

In [5]:
Xb,yb =load_boston(return_X_y=True)

df_boston = pd.DataFrame(Xb,columns = load_boston().feature_names)
df_boston.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10

In [3]:
df_boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB

In [4]:
df_boston.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [6]:
df_boston.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [7]:
corr = df_boston.corr()
corr

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
CRIM,1.000000,-0.200469,0.406583,-0.055892,0.420972,-0.219247,0.352734,-0.379670,0.625505,0.582764,0.289946,-0.385064,0.455621
ZN,-0.200469,1.000000,-0.533828,-0.042697,-0.516604,0.311991,-0.569537,0.664408,-0.311948,-0.314563,-0.391679,0.175520,-0.412995
INDUS,0.406583,-0.533828,1.000000,0.062938,0.763651,-0.391676,0.644779,-0.708027,0.595129,0.720760,0.383248,-0.356977,0.603800
CHAS,-0.055892,-0.042697,0.062938,1.000000,0.091203,0.091251,0.086518,-0.099176,-0.007368,-0.035587,-0.121515,0.048788,-0.053929
NOX,0.420972,-0.516604,0.763651,0.091203,1.000000,-0.302188,0.731470,-0.769230,0.611441,0.668023,0.188933,-0.380051,0.590879
RM,-0.219247,0.311991,-0.391676,0.091251,-0.302188,1.000000,-0.240265,0.205246,-0.209847,-0.292048,-0.355501,0.128069,-0.613808
AGE,0.352734,-0.569537,0.644779,0.086518,0.731470,-0.240265,1.000000,-0.747881,0.456022,0.506456,0.261515,-0.273534,0.602339
DIS,-0.379670,0.664408,-0.708027,-0.099176,-0.769230,0.205246,-0.747881,1.000000,-0.494588,-0.534432,-0.232471,0.291512,-0.496996
RAD,0.625505,-0.311948,0.595129,-0.007368,0.611441,-0.209847,0.456022,-0.494588,1.000000,0.910228,0.464741,-0.444413,0.488676
TAX,0.582764,-0.314563,0.720760,-0.035587,0.668023,-0.292048,0.506456,-0.534432,0.910228,1.000000,0.460853,-0.441808,0.543993
PTRATIO,0.289946,-0.391679,0.383248,-0.121515,0.188933,-0.355501,0.261515,-0.232471,0.464741,0.460853,1.000000,-0.177383,0.374044
B,-0.385064,0.175520,-0.356977,0.048788,-0.380051,0.128069,-0.273534,0.291512,-0.444413,-0.441808,-0.177383,1.000000,-0.366087
LSTAT,0.455621,-0.412995,0.603800,-0.053929,0.590879,-0.613808,0.602339,-0.496996,0.488676,0.543993,0.374044,-0.366087,1.000000

In [8]:
df_boston.dropna()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [9]:
from sklearn.ensemble import IsolationForest
df_boston = IsolationForest(random_state=0).fit(df_boston)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Xb,yb, test_size=0.3, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score

In [12]:
ridge_model1 = Ridge(alpha = 0.02)
ridge_model1.fit(X_train, y_train)

print(f'Ridge model coef: {ridge_model1.coef_}')

Ridge model coef: [-1.33268325e-01  3.58484549e-02  4.83016687e-02  3.11482496e+00
 -1.51257235e+01  4.05814278e+00 -1.10753008e-02 -1.38158181e+00
  2.42021805e-01 -8.72686117e-03 -9.07418824e-01  1.18013519e-02
 -5.47680892e-01]

In [17]:
ridge_model2 = Ridge(alpha = 0.04)
ridge_model2.fit(X_train, y_train)

print(f'Ridge model coef: {ridge_model2.coef_}')

Ridge model coef: [-1.33074341e-01  3.58867153e-02  4.71261116e-02  3.10990869e+00
 -1.48451760e+01  4.05902325e+00 -1.13200445e-02 -1.37732978e+00
  2.41344143e-01 -8.75063878e-03 -9.04275442e-01  1.18083295e-02
 -5.48229981e-01]

In [18]:
ridge_model3 = Ridge(alpha = 0.06)
ridge_model3.fit(X_train, y_train)

print(f'Ridge model coef: {ridge_model3.coef_}')

Ridge model coef: [-1.32887723e-01  3.59237644e-02  4.59934950e-02  3.10508143e+00
 -1.45748301e+01  4.05984407e+00 -1.15555966e-02 -1.37323318e+00
  2.40692829e-01 -8.77361337e-03 -9.01248349e-01  1.18150628e-02
 -5.48761585e-01]

In [19]:
ridge_model4 = Ridge(alpha = 0.08)
ridge_model4.fit(X_train, y_train)

print(f'Ridge model coef: {ridge_model4.coef_}')

Ridge model coef: [-1.32708076e-01  3.59596669e-02  4.49015172e-02  3.10033866e+00
 -1.43141392e+01  4.06060846e+00 -1.17824500e-02 -1.36928369e+00
  2.40066450e-01 -8.79582783e-03 -8.98331312e-01  1.18215647e-02
 -5.49276639e-01]

In [20]:
ridge_model5 = Ridge(alpha = 0.1)
ridge_model5.fit(X_train, y_train)

print(f'Ridge model coef: {ridge_model5.coef_}')

Ridge model coef: [-1.32535034e-01  3.59944827e-02  4.38480378e-02  3.09567615e+00
 -1.40625952e+01  4.06131940e+00 -1.20010626e-02 -1.36547356e+00
  2.39463689e-01 -8.81732204e-03 -8.95518536e-01  1.18278475e-02
 -5.49776010e-01]

<b>For Ridge model; as alpha goes up, model coef goes up at the same time.</b>

In [40]:
lasso_model1 = Lasso(alpha = 0.001)
lasso_model1.fit(X_train, y_train)

print(f'Lasso model coef: {lasso_model1.coef_}')

Lasso model coef: [-1.33223207e-01  3.58541994e-02  4.80415001e-02  3.10218343e+00
 -1.50654402e+01  4.05653876e+00 -1.10833360e-02 -1.38031239e+00
  2.41912162e-01 -8.73200965e-03 -9.06764520e-01  1.18043635e-02
 -5.47993456e-01]

In [41]:
lasso_model2 = Lasso(alpha = 0.003)
lasso_model2.fit(X_train, y_train)

print(f'Lasso model coef: {lasso_model2.coef_}')

Lasso model coef: [-1.32729716e-01  3.59447125e-02  4.50793388e-02  3.06688105e+00
 -1.43622954e+01  4.05522019e+00 -1.16084478e-02 -1.36894303e+00
  2.40282516e-01 -8.79155862e-03 -8.98924452e-01  1.18248600e-02
 -5.49753040e-01]

In [42]:
lasso_model3 = Lasso(alpha = 0.005)
lasso_model3.fit(X_train, y_train)

print(f'Lasso model coef: {lasso_model3.coef_}')

Lasso model coef: [-1.32236581e-01  3.60354009e-02  4.21167081e-02  3.03157633e+00
 -1.36591798e+01  4.05389749e+00 -1.21334562e-02 -1.35757614e+00
  2.38654157e-01 -8.85114804e-03 -8.91084496e-01  1.18453530e-02
 -5.51512773e-01]

In [43]:
lasso_model4 = Lasso(alpha = 0.007)
lasso_model4.fit(X_train, y_train)

print(f'Lasso model coef: {lasso_model4.coef_}')

Lasso model coef: [-1.31743293e-01  3.61261727e-02  3.91523506e-02  2.99627413e+00
 -1.29560311e+01  4.05257171e+00 -1.26583601e-02 -1.34621112e+00
  2.37024388e-01 -8.91066586e-03 -8.83243167e-01  1.18658315e-02
 -5.53272771e-01]

In [44]:
lasso_model5 = Lasso(alpha = 0.009)
lasso_model5.fit(X_train, y_train)

print(f'Lasso model coef: {lasso_model5.coef_}')

Lasso model coef: [-1.31250004e-01  3.62170945e-02  3.61877281e-02  2.96096948e+00
 -1.22528268e+01  4.05124170e+00 -1.31831199e-02 -1.33484564e+00
  2.35394976e-01 -8.97021585e-03 -8.75400976e-01  1.18863079e-02
 -5.55033399e-01]

<b>Unlike Ridge Model, in Lasso Model, as alpha goes up, model coef decreases.</b>

<b>According to results, higher alpha is better for ridge model and lower alpha is better for lasso model.</b>